name: 'Github Action: Deploy Shipa App'
description: 'Deploys Shipa Application'
inputs:
  file-path:
    description: 'File path to Shipa appDeploy.yml'
    required: true
runs:
  using: 'docker'
  image: 'vmanilo/shipa-action:0.0.2'
  args:
    - appDeploy
    - ${{ inputs.file-path }}